name: CICD

on: push

jobs:
  autorun:
    name: Server Task-Manager
    runs-on: self-hosted
    steps:
    
      - name: Kopieren der Dateien
        run: echo "Hello"
        
      - name: Neustart des HTTP Servers
        run: echo "Hello2"
        
      - name: Neustart des WebSockets
        run: echo "Hello3"
